version: '3.8'
services:
  bot:
    build: 
      context: .
      dockerfile: ./bot/Dockerfile
    env_file:
      - .env
    environment:
      - API_REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    container_name: redis
    build: 
      context: .
      dockerfile: .redis_db/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 
    ports:
      - 6379:6379